# Cumputer Oriented Numerical Method (book name)

### Solving 2-variable equation:(Page No. 1)

In [1]:
import numpy as np

def solve1(eq0,eq1):
    coeff = np.zeros((2,3),dtype=np.float16)
    row,col = coeff.shape
    coeff[0]=eq0
    coeff[1]=eq1
#     coeff[0]=[1,2,3]
#     coeff[1]=[2,3,4]
#     coeff[0]=[float(i) for i in input('Enter coefficients for 1st equation:\n').split(' ')]
#     coeff[1]=[float(i) for i in input('Enter coefficients for 2nd equation:\n').split(' ')]

    if coeff[0,1]*coeff[1,0] > coeff[0,0]*coeff[1,1]:
        for c in range(col):
            coeff[0,c],coeff[1,c]=coeff[1,c],coeff[0,c]

    print('Set of coefficients were:\n {}'.format(coeff))

    coeff[1,1]-=coeff[1,0]*coeff[0,1]/coeff[0,0]
    coeff[1,2]-=coeff[1,0]*coeff[0,2]/coeff[0,0]

    if coeff[1,1]<0.000001:
        print('No solution')
        return

    y=coeff[1,2]/coeff[1,1]
    x=(coeff[0,2]-coeff[0,1]*y)/coeff[0,0]

    print('result: x={} and y={}'.format(x,y))
    return

solve1([1,2,3],[2,3,4])

Set of coefficients were:
 [[ 2.  3.  4.]
 [ 1.  2.  3.]]
result: x=-1.0 and y=2.0


In [34]:
coeff

array([[ 5.,  6.,  7.],
       [ 2.,  3.,  4.]], dtype=float16)

### Solving the fibonacci series: (Page No. 6)

In [44]:
n1,n2=[float(i) for i in input('enter initial values:\n').split(' ')]
n=int(input('enter number of terms:\n'))
if n>=1:
    print(n1)
if n>=2:
    print(n2)
if n>2:
    for i in range(2,n):
        n1,n2=n2,n1+n2
        print(n2)

enter initial values:
1 2
enter number of terms:
2
1.0
2.0


### Generating values for infinite series expansion (till finite terms) (Page No. 9)

#### Method: 1

In [55]:
# x,n = [float(i) for i in input('Enter x and n:\n').split(' ')]
x,n = 1,2
n = int(n)
term,res=x,x
for i in range(1,n):
    term = -1*x*x*term/(2*i*(2*i+1))
    res += term
print(res)

0.8333333333333334


#### Method: 2

In [54]:
# x,n = [float(i) for i in input('Enter x and n:\n').split(' ')]
x,n = 1,2
n = int(n)
if n==1:
    print(x)
else:
    n-=1
    res=-1*x*x/(2*n*(2*n+1))
    for i in range(n-1,0,-1):
        res+=1
        res*=-1*x*x/(2*i*(2*i+1))
    res+=1
    res*=x
    print(res)

0.8333333333333334


### Polynomial division (Page No. 11)

In [9]:
def divide(a,b):

    n=len(a)-1
    r=len(b)-1

    if r>n:
        return
    Q=[0 for i in range(n-r+1)]
    for i in range(n-r+1):
        Q[n-r-i]=a[n-i]
        for j in range(i):
            if j not in range(r):
                break
            Q[n-r-i]-=Q[n-r-j]*b[r-i+j]
        Q[n-r-i]/=b[r]
    return Q
# Constant coefficient first
# a=[float(i) for i in input('Enter coefficients ai:\n').split(' ')]
# b=[float(i) for i in input('Enter coefficients bi:\n').split(' ')]
a=[1,2,3]
b=[1,2]
Q=divide(a,b)
print('Quotient is:\n{}'.format(Q))

Quotient is:
[0.25, 1.5]


### Polynomial roots: (Chapter 3)

In [23]:
import math

# Constant coefficient first
# a=[float(i) for i in input('Enter coefficients ai:\n').split(' ')]
a=[-25,0,1]

n=len(a)-1
s_range=math.sqrt((a[n-1]/a[n])**2-2*(a[n-2]/a[n]))
# print(s_range)

def f(a,x):
    n=len(a)-1
    res=0
    for i in range(n+1):
        res+=a[i]*math.pow(x,i)
    return res

n1,n2=-s_range,s_range

def bisection_method(n1,n2,f1,f2):
    mid=(n1+n2)/2
    f_mid=f(a,mid)
    if f1*f_mid<0:
        return n1,mid
    elif f2*f_mid<0:
        return n2,mid
    elif abs(f1)>abs(f_mid):
        return n2,mid
    elif abs(f2)>abs(f_mid):
        return n1,mid
    
def false_position_method(n1,n2,f1,f2):
    if abs(f1-f2)<0.1:
        mid=(n1+n2)/2
    else:
        mid=(n1*f2-n2*f1)/(f2-f1)
    f_mid=f(a,mid)
    if f1*f_mid<0:
        return n1,mid
    elif f2*f_mid<0:
        return n2,mid
    elif abs(f1)>abs(f_mid):
        return n2,mid
    elif abs(f2)>abs(f_mid):
        return n1,mid

# while abs(n1-n2)>0.1:
#     f1=f(a,n1)
#     f2=f(a,n2)
#     n1,n2=bisection_method(n1,n2,f1,f2)
#     n1,n2=false_position_method(n1,n2,f1,f2)
#     print(n1,n2,f1,f2)
# print('result {}'.format((n1+n2)/2))

def newton_rephson(a,n2,f2):
    Q=divide(a,[-n2,1])
    df2=f(Q,n2)
    if df2==0:
        return False,n2
    n2=n2-f2/df2
    return True,n2

def secant_method(a,n2,f2):
    n3=n2+0.1
    f3=f(a,n3)
    if abs(f2-f3)<0.1:
        return False,(n3+n2)/2
    else:
        n2=(n3*f2-n2*f3)/(f2-f3)
        return True, n2

count=0
f2=f(a,n2)
status=True
while status==True and count<10 and f2>0.1:
#     status,n2=newton_rephson(a,n2,f2)
    status,n2=secant_method(a,n2,f2)
    f2=f(a,n2)
    count+=1
    print(n2,f2,df2)
print('result {}'.format(n2))

5.315713091163068 3.2568056675624177 10.606601717798213
5.012230067357141 0.12245024811896954 10.606601717798213
5.000135570812173 0.0013557265011741038 10.606601717798213
result 5.000135570812173


### Solution of simultaneous equation (Chapter 4)

#### Method-1: Gauss elimination method

In [1]:
import numpy as np

# Input
# m = int(input('Enter number of equation:\n'))

# coeff=np.zeros((m,m+1),dtype=np.float16)
# for i in range(m):
#     temp=[float(i) for i in input('Enter coeff for eq:{}\n'.format(i+1)).split(' ')]
#     assert len(temp)==m+1
#     coeff[i]=temp
    
# print(coeff)
m=3
coeff=np.array([[2,3,5,23],[3,4,1,14],[6,7,2,26]],dtype=np.float16)

def swap(coeff,row1,row2,m):
    for i in range(m+1):
        coeff[row1,i],coeff[row2,i]=coeff[row2,i],coeff[row1,i]

def Gauss_elim(coeff,m):
    if type(coeff)==list:
        coeff=np.array(coeff,dtype=np.float16)
    # pivoting
    r,c=coeff.shape
    lst=[]
    for count in range(r):
        for i in range(r):
            if i in lst:continue
            maxm=coeff[i,i]
            ind=(i,i)
            for j in range(c-1):
                if j in lst:continue
                if coeff[i,j]>maxm:
                    maxm=coeff[i,j]
                    ind=(i,j)
        if ind[0]!=ind[1]:
            swap(coeff,ind[0],ind[1],c-1)
        lst.append(ind[1])

    print(coeff)

    # triangulation
    for row1 in range(m-1):
        for row2 in range(row1+1,m):
            temp=[coeff[row2,row1],coeff[row1,row1]]
            for col in range(4):
                coeff[row2,col]=coeff[row2,col]-coeff[row1,col]*temp[0]/temp[1]

    # print(coeff)

    # Generating result
    result=np.zeros((1,m),dtype=np.float16)
    for row in range(m-1,-1,-1):
        temp=coeff[row,m]
        for col in range(row,m):
            temp-=coeff[row,col]*result[0,col]
        temp/=coeff[row,row]
        result[0,row]=temp
    print(result)
    return result

Gauss_elim(coeff,m)

[[  3.   4.   1.  14.]
 [  6.   7.   2.  26.]
 [  2.   3.   5.  23.]]
[[ 1.  2.  3.]]


array([[ 1.,  2.,  3.]], dtype=float16)

#### Method-2: Gauss Iterative method

In [2]:
import numpy as np

# Input
# m = int(input('Enter number of equation:\n'))

# coeff=np.zeros((m,m+1),dtype=np.float16)
# for i in range(m):
#     temp=[float(i) for i in input('Enter coeff for eq:{}\n'.format(i+1)).split(' ')]
#     assert len(temp)==m+1
#     coeff[i]=temp
    
# print(coeff)
m=3
coeff=np.array([[2,3,5,23],[3,4,1,14],[6,7,2,26]],dtype=np.float16)

def swap(coeff,row1,row2,m):
    for i in range(m+1):
        coeff[row1,i],coeff[row2,i]=coeff[row2,i],coeff[row1,i]

# pivoting
def pivot(coeff):
    r,c=coeff.shape
    lst=[]
    for count in range(r):
        for i in range(r):
            if i in lst:continue
            maxm=coeff[i,i]
            ind=(i,i)
            for j in range(c-1):
                if j in lst:continue
                if coeff[i,j]>maxm:
                    maxm=coeff[i,j]
                    ind=(i,j)
        print(ind,coeff[ind])
        if ind[0]!=ind[1]:
            swap(coeff,ind[0],ind[1],c-1)
        lst.append(ind[1])
    return coeff

def Gauss_iter(coeff,m):
    if type(coeff)==list:
        coeff=np.array(coeff,dtype=np.float16)
    coeff=pivot(coeff)
    print(coeff)
    result1=np.zeros((1,m),dtype=np.float16)
    result2=np.zeros((1,m),dtype=np.float16)
    count=0
    while count<50:
        for i in range(m):
            temp=coeff[i,m]
            for j in range(m):
                if j==i:
                    continue
                temp-=result2[0,j]*coeff[i,j]
            temp/=coeff[i,i]
            result2[0,i]=temp
        print(count,result2)
        if np.linalg.norm(result1-result2)<0.01:
            break
        result1=result2.copy()
        count+=1
    return result2

Gauss_iter(coeff,m)

(2, 1) 7.0
(2, 0) 3.0
(2, 2) 5.0
[[  3.   4.   1.  14.]
 [  6.   7.   2.  26.]
 [  2.   3.   5.  23.]]
0 [[ 4.66796875 -0.28564453  2.90429688]]
1 [[ 4.078125   -0.61083984  3.33398438]]
2 [[ 4.3671875  -0.98144531  3.44335938]]
3 [[ 4.82421875 -1.40429688  3.51171875]]
4 [[ 5.37109375 -1.89160156  3.58789062]]
5 [[ 5.98828125 -2.44335938  3.66796875]]
6 [[ 6.703125   -3.08007812  3.76953125]]
7 [[ 7.515625   -3.80273438  3.875     ]]
8 [[ 8.4453125 -4.6328125  4.       ]]
9 [[ 9.5078125  -5.58203125  4.1484375 ]]
10 [[ 10.71875     -6.66015625   4.30859375]]
11 [[ 12.1015625   -7.89453125   4.49609375]]
12 [[ 13.6875      -9.3046875    4.70703125]]
13 [[ 15.5        -10.921875     4.94921875]]
14 [[ 17.578125   -12.765625     5.23046875]]
15 [[ 19.953125   -14.8828125    5.55078125]]
16 [[ 22.640625  -17.28125     5.9140625]]
17 [[ 25.734375   -20.03125      6.32421875]]
18 [[ 29.265625   -23.171875     6.79296875]]
19 [[ 33.28125   -26.765625    7.3515625]]
20 [[ 37.90625   -30.89062

array([[ 1777.   , -1581.   ,   242.375]], dtype=float16)

### Integration (Chapter 8)

#### Method-1: Trapezoidal rule

In [71]:
# input
# x=[float(i) for i in input('Enter x-list:\n').split(' ')]
# y=[float(i) for i in input('Enter y-list:\n').split(' ')]
x=[0.25,0.26,0.27,0.28,0.29]
y=[0.2474,0.2571,0.2667,0.2764,0.2860]
assert len(x)==len(y)
i_res=0
interval=len(x)-1
for i in range(interval):
    i_res+=0.5*(y[i]+y[i+1])*(x[i+1]-x[i])
print(i_res)

0.010668999999999993


#### Simpson's rule

In [75]:
# input: assumption 'x' is equally spaced
# x=[float(i) for i in input('Enter x-list:\n').split(' ')]
# y=[float(i) for i in input('Enter y-list:\n').split(' ')]
x=[0.25,0.26,0.27,0.28,0.29]
y=[0.2474,0.2571,0.2667,0.2764,0.2860]

interval=len(x)-1
h=x[1]-x[0]
for i in range(1,interval-1):
    assert x[i+1]-x[i]==h
assert len(x)==len(y)

i_res=0
for i in range(0,interval,2):
    i_res+=h*(y[i]+4*y[i+1]+y[i+2])/3
print(i_res)

0.010669333333333343


### Least square approximation of the function (Chapter 6)

In [3]:
x=[1,2,4,5,6,8,9]
y=[2,5,7,10,12,15,19]
order=2
n=len(x)

eq_lst=[]
for eq in range(order+1):
    temp=[]
    if eq==0:
        for power in range(order+1):
            temp.append(sum([pow(base,power) for base in x]))
    else:
        temp=eq_lst[-1][1:-1]
        temp.append(sum([pow(base,eq+order) for base in x]))
    temp.append(sum([pow(base,eq)*out for base,out in zip(x,y)]))
    eq_lst.append(temp)
print(eq_lst)
Gauss_elim(eq_lst,order+1)

[[7, 35, 227, 70], [35, 227, 1655, 453], [227, 1655, 12851, 3315]]
[[  7.00000000e+00   3.50000000e+01   2.27000000e+02   7.00000000e+01]
 [  3.50000000e+01   2.27000000e+02   1.65500000e+03   4.53000000e+02]
 [  2.27000000e+02   1.65500000e+03   1.28480000e+04   3.31600000e+03]]
[[ nan  nan  nan]]


C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:47: RuntimeWarning: overflow encountered in half_scalars
C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:56: RuntimeWarning: invalid value encountered in half_scalars


array([[ nan,  nan,  nan]], dtype=float16)

In [4]:
x=[1,2,4,5,6,8,9]
y=[2,5,7,10,12,15,19]
order=2
n=len(x)
mean=sum(x)/n
x=[i-mean for i in x]

eq_lst=[]
for eq in range(order+1):
    temp=[]
    if eq==0:
        for power in range(order+1):
            temp.append(sum([pow(base,power) for base in x]))
    else:
        temp=eq_lst[-1][1:-1]
        temp.append(sum([pow(base,eq+order) for base in x]))
    temp.append(sum([pow(base,eq)*out for base,out in zip(x,y)]))
    eq_lst.append(temp)
print(eq_lst)
coeff=Gauss_elim(eq_lst,order+1)

res=coeff.copy()
for o in range(order,0,-1):
    temp=1
    for i in range(o-1,-1,-1):
        temp*=(-mean)*(i+1)/(o-i)
        res[0,i]+=temp*coeff[0,o]
        print(mean,i,o,temp,res[0,i],coeff[0,o])
    print(res)

[[7.0, 0.0, 52.0, 70.0], [0.0, 52.0, 0.0, 103.0], [52.0, 0.0, 676.0, 535.0]]
[[   7.    0.   52.   70.]
 [   0.   52.    0.  103.]
 [  52.    0.  676.  535.]]
[[ 9.6171875   1.98046875  0.05175781]]
5.0 1 2 -10.0 1.4629 0.051758
5.0 0 2 25.0 10.914 0.051758
[[ 10.9140625    1.46289062   0.05175781]]
5.0 0 1 -5.0 1.0117 1.9805
[[ 1.01171875  1.46289062  0.05175781]]


## Interpolation (Chapter 5)

### Lagrange Polynomial

In [11]:
x=[1.5,3,6]
y=[-0.25,2,20]

x_res,y_res=4,0
n=len(x)
assert len(x)==len(y)
for i in range(n):
    temp=y[i]
    for j in range(n):
        if i==j:continue
        temp*=(x_res-x[j])/(x[i]-x[j])
    y_res+=temp
print(y_res)

6.0


### Divided difference (forward)

In [28]:
x=[1921,1931,1941,1951,1961,1971,1981]
y=[35,42,58,84,120,165,220]

x_res,y_res=1925,0
n=len(x)
diff_table=y.copy()

# creating the difference table
for i in range(n):
    for j in range(n-1,i,-1):
        diff_table[j]=(diff_table[j]-diff_table[j-1])/(x[j]-x[j-i-1])
print('difference_table_coeff:{}'.format(diff_table))

# formulating the equation
for i in range(1,n):
    for j in range(i,n):
        diff_table[j]*=(x_res-x[i-1])
#     print(diff_table)
    
print('result:{}'.format(sum(diff_table)))

difference_table_coeff:[35, 0.7, 0.045000000000000005, 0.00016666666666666658, -4.166666666666664e-06, -1.1858461261560206e-22, 4.166666666666672e-09]
result:36.7567104


### Cubic spline

In [46]:
x=[1,2,3,4,5]
y=[30,15,32,18,25]

assert len(x)==len(y)
n=len(x)

coeff=np.zeros((n-2,n+1),dtype=np.float16)
for i in range(n-2):
    coeff[i,i:i+3]=[x[i+1]-x[i],2*(x[i+2]-x[i]),x[i+2]-x[i+1]]
    coeff[i,-1]=6*((y[i+2]-y[i+1])/(x[i+2]-x[i+1])-(y[i+1]-y[i])/(x[i+1]-x[i]))

print('actual equation coefficients:\n{}'.format(coeff))

lst=list(range(n))
ddiff=np.zeros((n,1),dtype=np.float16)
# for i in range(2):
#     ind,val=[float(i) for i in input('enter index and value').split(' ')]
#     ind=int(ind)
for ind,val in [(0,10),(4,10)]:
    assert ind in lst
    for i in range(n-2):
        coeff[i,-1]-=(coeff[i,ind]*val)
    ddiff[ind,0]=val
    lst.remove(ind)

lst.append(n)
coeff=coeff[:,lst]
print(coeff)
dcoeff=Gauss_elim(coeff,n-2)
print(dcoeff)
lst.remove(n)
for i,j in zip(lst,dcoeff[0]):
    ddiff[i,0]=j
    
def f(x_val,i1,i2,ddiff,x,y):
    return (ddiff[i1]*(x_val-x[i2])**3/(6*(x[i1]-x[i2]))+ddiff[i2]*(x_val-x[i1])**3/(6*(x[i2]-x[i1]))+
            (y[i2]/(x[i2]-x[i1])-ddiff[i2]*(x[i2]-x[i1])/6)*(x_val-x[i1])+
            (y[i1]/(x[i1]-x[i2])-ddiff[i1]*(x[i1]-x[i2])/6)*(x_val-x[i2]))

actual equation coefficients:
[[   1.    4.    1.    0.    0.  192.]
 [   0.    1.    4.    1.    0. -186.]
 [   0.    0.    1.    4.    1.  126.]]
[[   4.    1.    0.  182.]
 [   1.    4.    1. -186.]
 [   0.    1.    4.  116.]]
[[   4.    1.    0.  182.]
 [   1.    4.    1. -186.]
 [   0.    1.    4.  116.]]
[[ 64.125   -74.375    47.59375]]
[[ 64.125   -74.375    47.59375]]


In [47]:
f(3.5,3,4,ddiff,x,y)

array([ 30.], dtype=float16)